// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB65b9q5ehnE3CwhGBh1tNJeAaz75v_u70',
    appId: '1:247292569309:web:378b298c30ca98d4209d34',
    messagingSenderId: '247292569309',
    projectId: 'nayem-e0f76',
    authDomain: 'nayem-e0f76.firebaseapp.com',
    storageBucket: 'nayem-e0f76.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALVUSgvxq_yLnYnnRhAJawC-XOr4TrQ28',
    appId: '1:247292569309:android:263896b1cfc16779209d34',
    messagingSenderId: '247292569309',
    projectId: 'nayem-e0f76',
    storageBucket: 'nayem-e0f76.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH_RuOECaW9rLrQ8myDimABiD9T3JFJ3s',
    appId: '1:247292569309:ios:5e5b04ffae446bf5209d34',
    messagingSenderId: '247292569309',
    projectId: 'nayem-e0f76',
    storageBucket: 'nayem-e0f76.firebasestorage.app',
    iosBundleId: 'com.example.flutterGsignIn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH_RuOECaW9rLrQ8myDimABiD9T3JFJ3s',
    appId: '1:247292569309:ios:5e5b04ffae446bf5209d34',
    messagingSenderId: '247292569309',
    projectId: 'nayem-e0f76',
    storageBucket: 'nayem-e0f76.firebasestorage.app',
    iosBundleId: 'com.example.flutterGsignIn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB65b9q5ehnE3CwhGBh1tNJeAaz75v_u70',
    appId: '1:247292569309:web:38dae6585145b3f1209d34',
    messagingSenderId: '247292569309',
    projectId: 'nayem-e0f76',
    authDomain: 'nayem-e0f76.firebaseapp.com',
    storageBucket: 'nayem-e0f76.firebasestorage.app',
  );
}
